# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-02-26 03:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Passengersinfo',
            fields=[
                ('passengerid', models.IntegerField(db_column='PassengerId', primary_key=True, serialize=False)),
                ('pclass', models.IntegerField(db_column='Pclass')),
                ('name', models.CharField(blank=True, db_column='Name', max_length=100, null=True)),
                ('sex', models.CharField(blank=True, db_column='Sex', max_length=10, null=True)),
                ('age', models.IntegerField(blank=True, db_column='Age', null=True)),
                ('sibsp', models.CharField(blank=True, db_column='SibSp', max_length=10, null=True)),
                ('parch', models.CharField(blank=True, db_column='Parch', max_length=10, null=True)),
                ('ticket', models.CharField(blank=True, db_column='Ticket', max_length=20, null=True)),
                ('fare', models.FloatField(blank=True, db_column='Fare', null=True)),
                ('cabin', models.CharField(blank=True, db_column='Cabin', max_length=50, null=True)),
                ('embarked', models.CharField(blank=True, db_column='Embarked', max_length=10, null=True)),
            ],
            options={
                'db_table': 'PassengersInfo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameOfHoli', models.CharField(blank=True, max_length=10, verbose_name='假期名称')),
                ('dateOfHoli', models.DateField(blank=True, null=True, verbose_name='假期日期')),
            ],
            options={
                'verbose_name': '公休假期表',
            },
        ),
        migrations.CreateModel(
            name='NoteForLeave',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateOfStart', models.DateField(blank=True, null=True, verbose_name='开始时间')),
                ('dateOfEnd', models.DateField(blank=True, null=True, verbose_name='结束时间')),
                ('destination', models.CharField(max_length=50, null=True, verbose_name='目的地')),
                ('toolOff', models.CharField(max_length=50, null=True, verbose_name='交通工具')),
                ('dateOfAdd', models.DateField(auto_now_add=True, verbose_name='请假时间')),
                ('dateOfCancel', models.DateField(auto_now=True, verbose_name='销假时间')),
                ('apprFlag', models.NullBooleanField(verbose_name='本级审批情况')),
                ('apprUpperFlag', models.NullBooleanField(verbose_name='上级审批情况')),
                ('contact', models.CharField(max_length=10, null=True, verbose_name='联系人')),
                ('contactPhone', models.CharField(max_length=15, null=True, verbose_name='联系电话')),
            ],
            options={
                'verbose_name': '请假记录表',
            },
        ),
        migrations.CreateModel(
            name='TypeOfVacation',
            fields=[
                ('idVacation', models.IntegerField(primary_key=True, serialize=False)),
                ('holiType', models.CharField(max_length=10, verbose_name='请假类型')),
                ('marryOrNot', models.NullBooleanField(verbose_name='婚否')),
                ('sepWithCouple', models.NullBooleanField(verbose_name='两地分居')),
                ('sepWithParent', models.NullBooleanField(verbose_name='与父母异地')),
                ('serMeet10', models.NullBooleanField(verbose_name='服役满10年')),
                ('serMeet20', models.NullBooleanField(verbose_name='服役满20年')),
                ('daysOfVacation', models.IntegerField(null=True, verbose_name='假期天数')),
            ],
            options={
                'verbose_name': '休假类型表',
                'ordering': ['idVacation'],
            },
        ),
        migrations.CreateModel(
            name='TableOfInfo',
            fields=[
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='VacationSys.Passengersinfo')),
                ('daysOfRoad', models.IntegerField(default=0, verbose_name='路途')),
                ('sepWithCouple', models.NullBooleanField(verbose_name='两地分居')),
                ('sepWithParent', models.NullBooleanField(verbose_name='与父母异地')),
                ('daysLeft', models.IntegerField(default=0, verbose_name='剩余天数')),
                ('status', models.CharField(choices=[('in', 'IN'), ('out', 'OUT')], default='in', max_length=5, verbose_name='在位情况')),
                ('holiType', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='VacationSys.TypeOfVacation', verbose_name='休假类型')),
            ],
            options={
                'verbose_name': '请假信息维护表',
            },
        ),
        migrations.AddField(
            model_name='noteforleave',
            name='holiType',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='VacationSys.TypeOfVacation', verbose_name='请假类型'),
        ),
        migrations.AddField(
            model_name='noteforleave',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='VacationSys.Passengersinfo'),
        ),
    ]
